apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: web-http
  - port: 8443
    targetPort: 443
    nodePort: 30443
    name: web-https
  selector:
    name: zabbix-web
  sessionAffinity: None
  type: NodePort