#apiVersion: v1
#kind: Service
#metadata:
#  name: mysql-server
#  labels:
#    app: zabbix
#  namespace: zabbix
#spec:
#  type: ClusterIP
#  ports:
#  - port: 3306
#    targetPort: 3306
#    name: mysql-server
#  selector:
#    name: mysql-server

apiVersion: v1
kind: Service
metadata:
  namespace: zabbix
  name: mysql-server
  labels:
    app: zabbix
    tier: mysql-server
spec:
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: zabbix
    tier: mysql-server